services:
  nginx:
    image: nginx:alpine
    container_name: prbrazil-fullcycle-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build:
      context: node
    container_name: prbrazil-fullcycle-app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s docker-entrypoint.sh index.js
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=Pessoa
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: prbrazil-fullcycle-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Pessoa
    ports:
      - "3306:3306"
    volumes:
      - volume-mysql:/var/lib/mysql

volumes:
  volume-mysql:
    driver: local
