services:
  nginx:
    image: nginx:alpine
    container_name: prbrazil-fullcycle-nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prbrazil-fullcycle-app
    volumes:
      - ./src:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=Pessoa
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: prbrazil-fullcycle-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Pessoa
    ports:
      - "3306:3306"
    volumes:
      - volume-mysql:/var/lib/mysql

volumes:
  volume-mysql:
    driver: local
